In [15]:
import pandas as pd

df = pd.read_csv(r"C:\Users\ghole\Downloads\customer_shopping_behavior.csv")

In [17]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [18]:
%whos

Variable        Type         Data/Info
--------------------------------------
create_engine   function     <function create_engine at 0x00000188A47084A0>
database        str          demodb
df              DataFrame    Shape: (3900, 18)
engine          Engine       Engine(postgresql+psycopg<...>**@localhost:5432/demodb)
host            str          localhost
password        str          Nairin16
pd              module       <module 'pandas' from 'C:<...>es\\pandas\\__init__.py'>
port            str          5432
table_name      str          customer1
username        str          postgres

In [3]:
import os
os.getcwd()

'C:\\Users\\ghole'

In [4]:
os.listdir()

['.anaconda',
 '.conda',
 '.continuum',
 '.eclipse',
 '.ipynb_checkpoints',
 '.ipython',
 '.jupyter',
 '.p2',
 '.VirtualBox',
 '.vscode',
 'AppData',
 'Application Data',
 'Contacts',
 'Cookies',
 'Document_new',
 'Document_old',
 'Downloads',
 'eclipse',
 'eclipse-workspace',
 'edb_pgagent_pg18.exe',
 'edb_pgbouncer.exe',
 'edb_pgjdbc.exe',
 'edb_psqlodbc.exe',
 'edb_psqlodbc.exe-20251123141600',
 'Favorites',
 'Links',
 'Local Settings',
 'Music',
 'My Documents',
 'NetHood',
 'NTUSER.DAT',
 'ntuser.dat.LOG1',
 'ntuser.dat.LOG2',
 'NTUSER.DAT{4c62b170-3a73-11f0-b65f-f83dc659b84b}.TxR.0.regtrans-ms',
 'NTUSER.DAT{4c62b170-3a73-11f0-b65f-f83dc659b84b}.TxR.0.regtrans-ms.cnpf',
 'NTUSER.DAT{4c62b170-3a73-11f0-b65f-f83dc659b84b}.TxR.1.regtrans-ms',
 'NTUSER.DAT{4c62b170-3a73-11f0-b65f-f83dc659b84b}.TxR.1.regtrans-ms.cnpf',
 'NTUSER.DAT{4c62b170-3a73-11f0-b65f-f83dc659b84b}.TxR.2.regtrans-ms',
 'NTUSER.DAT{4c62b170-3a73-11f0-b65f-f83dc659b84b}.TxR.2.regtrans-ms.cnpf',
 'NTUSER.DAT{4c62b170-3a73-11f0-b65f-f83dc659b84b}.TxR.blf',
 'NTUSER.DAT{4c62b170-3a73-11f0-b65f-f83dc659b84b}.TxR.blf.cnpf',
 'NTUSER.DAT{4c62b171-3a73-11f0-b65f-f83dc659b84b}.TM.blf',
 'NTUSER.DAT{4c62b171-3a73-11f0-b65f-f83dc659b84b}.TM.blf.cnpf',
 'NTUSER.DAT{4c62b171-3a73-11f0-b65f-f83dc659b84b}.TMContainer00000000000000000001.regtrans-ms',
 'NTUSER.DAT{4c62b171-3a73-11f0-b65f-f83dc659b84b}.TMContainer00000000000000000001.regtrans-ms.cnpf',
 'NTUSER.DAT{4c62b171-3a73-11f0-b65f-f83dc659b84b}.TMContainer00000000000000000002.regtrans-ms',
 'NTUSER.DAT{4c62b171-3a73-11f0-b65f-f83dc659b84b}.TMContainer00000000000000000002.regtrans-ms.cnpf',
 'ntuser.ini',
 'OneDrive',
 'postgresql_18.exe',
 'PrintHood',
 'Recent',
 'Saved Games',
 'Searches',
 'SendTo',
 'Start Menu',
 'Templates',
 'Untitled.ipynb',
 'Videos',
 'VirtualBox VMs',
 'WPS Cloud Files',
 'WPSDrive']

In [5]:
df = pd.read_csv(r"C:\Users\ghole\Downloads\customer_shopping_behavior.csv")

In [6]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [8]:
df.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3900.000000,3900.000000,3863.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.750065,25.351538
std,1125.977353,15.207589,23.685392,0.716983,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.800000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

In [9]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [10]:
df["Review Rating"] = df.groupby("Category")["Review Rating"].transform(
    lambda x: x.fillna(x.median())
)

In [11]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [17]:
df.columns=df.columns.str.lower()

df.columns=df.columns.str.replace(' ','_')

df=df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})

In [13]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_(usd)', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [18]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [21]:
#creating a new age group column
labels=['Yound Adult','Adult','Middle-Ages','Seniors']
df['age_group']=pd.qcut(df['age'],q=4, labels=labels)

In [22]:
df[['age','age_group']].head(10)

   age    age_group
0   55  Middle-Ages
1   19  Yound Adult
2   50  Middle-Ages
3   21  Yound Adult
4   45  Middle-Ages
5   46  Middle-Ages
6   63      Seniors
7   27  Yound Adult
8   26  Yound Adult
9   57  Middle-Ages

In [24]:
#create column purchase frequency days 
frequency_mapping={
    'Fortnightly':14,
    'Weekly':7,
    'Monthly':30,
    'Quaterly':90,
    'Bi-Weekly':14,
    'Annually':365,
    'Every 3 months':90}
df['purchase_frequency_days']=df['frequency_of_purchases'].map(frequency_mapping)

In [25]:
df[['purchase_frequency_days','frequency_of_purchases']].head(10)

   purchase_frequency_days frequency_of_purchases
0                     14.0            Fortnightly
1                     14.0            Fortnightly
2                      7.0                 Weekly
3                      7.0                 Weekly
4                    365.0               Annually
5                      7.0                 Weekly
6                      NaN              Quarterly
7                      7.0                 Weekly
8                    365.0               Annually
9                      NaN              Quarterly

In [26]:
df[['discount_applied','promo_code_used']].head(10)

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes
5              Yes             Yes
6              Yes             Yes
7              Yes             Yes
8              Yes             Yes
9              Yes             Yes

In [28]:
(df['discount_applied']==df['promo_code_used']).all()

np.True_

In [29]:
df=df.drop('promo_code_used',axis=1)

In [30]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='object')

In [1]:
pip install psycopg2-binary sqlalchemy

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: psycopg2-binary in c:\users\ghole\appdata\roaming\python\python313\site-packages (2.9.12)
Requirement already satisfied: sqlalchemy in c:\programdata\anaconda3\lib\site-packages (2.0.43)
Requirement already satisfied: greenlet>=1 in c:\programdata\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\programdata\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

In [28]:
# Step 1: Connect to PostgreSQL
# Replace placeholders with your actual details
from sqlalchemy import create_engine

username = "postgres"          # default user
password = "Nairin16"          # the password you set during installation
host = "localhost"             # if running locally
port = "5432"                  # default PostgreSQL port
database = "demodb" # the database you created in pgAdmin

engine = create_engine(
    f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}"
)

# Step 2: Load DataFrame into PostgreSQL

table_name = "customer1"  # choose any table name

df.to_sql(
    table_name,
    engine,
    if_exists="replace",
    index=False
)

print(f"Data successfully loaded into table '{table_name}' in database '{database}'.")

Data successfully loaded into table 'customer1' in database 'demodb'.

In [31]:
from sqlalchemy import create_engine

engine = create_engine(
    "postgresql+psycopg2://postgres:Nairin16@localhost:5432/demodb"
)

try:
    with engine.connect() as conn:
        print("Connected successfully!")
except Exception as e:
    print(e)

Connected successfully!